// <auto-generated />
namespace WindowsEFEscuela.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class lastlastMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastlastMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202301172040423_lastlastMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
